### ISSUE TITLE
Potential logic issue with URL structure

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#11]
Right now the URL structure of the member page is `/first-name/last-name`. However both of these fields are editable. Therefore, if a user changes their name, the URL of their profile URL will change. This could have some fairly negative SEO implications.

Just curious to get a pulse check on this. I'd like to include the name of the user in the URL. So maybe there is a way to build in URL redirection?

**Comment by d4mation** [comment]
The current way the plugin works isn't quite how a normal Custom Post Type Archive/Single would work, so I'm not too sure how much this would all apply. 

Each URL is being dynamically generated at the time of the query and when you're viewing a Member's profile, it grabs the `first_name` and `last_name` from the URL to use to query the user data. 

I guess what I'm trying to say is that as far as WordPress is concerned, the pages don't properly exist. They are accessible via their URLs and therefore should be indexable via a Search Engine, but no information about them is being stored in the Database outside of the data that belongs to the User that is used to generate their profile. 

Outside of keeping track of every name change in the Database and building 301 redirects accordingly, I'm not sure how we should handle it. 

What would you think about using their User Name for the URL instead? I know that's less preferable, but that would solve the issue of potentially changing URLs from the User changing their name as well something else I thought of:

What happens if two Users share the same name? For instance, something like "John Smith". WordPress normally tacks a number to the end of the slug in a case like this, but as I'm querying the User based on the URL that could prove problematic. 

If the URL matched their Username, this wouldn't be an issue since all Usernames are unique by nature.

**Comment by d4mation** [comment]
What do you think, @brashrebel?

**Comment by jrosebr1** [comment]
Good point on the username. That's probably the right way to go. And then just ensure the first and last name are included in both the `title` tag and meta description.

**Comment by d4mation** [comment]
Sounds good to me. I'll get the URLs in the plugin swapped over to use their Username and then ensure that their Name is making it into both the `title` and `meta` description.

**Comment by d4mation** [comment]
Quick question: Are you using Yoast SEO?

I have the plugin set to generate the `<title>` tag already, and it looks like if Yoast is installed, it automatically creates the `og:title` and `twitter:title` `<meta>` tags based on the Page Title.

For example:

`<meta property="og:title" content="Firstname Lastname | Your Site">`

Are you wanting any other information available in the `<meta>` tags?

**Comment by jrosebr1** [comment]
At the current time I am not using any SEO plugins for the Gurus course (
https://gurus.pyimagesearch.com/), mainly because most of the content is
paywalled. I don't think any other tags will be needed in the meta. You're
probably looking at the PyImageSearch site (http://www.pyimagesearch.com/)

**Comment by d4mation** [comment]
Ah, I see what you're saying.

The plugin is now set to generate and add `og:title` and `twitter:title` if Yoast SEO is not installed for both the Member Directory page and the individual Member Profiles. Figured I'd add that bit in there just in case.
