### ISSUE TITLE
Member directory updates

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#15]
The member directory page looks good. I've included a few comments in the attached image.
1. The links in the WordPress menu should default to the menu links selected in the backend. Right now it seems like the current page is being used as the links.
2. The profile pictures are a bit large at 96x96 pixels. Let's cut them down to 48x48 pixels.
3. Now that the profile pictures have been reduced, increase the number of users displayed page page from 15 to 20.
   ![member_page_01](https://cloud.githubusercontent.com/assets/759645/14562512/18e1b246-02eb-11e6-954a-a5efdef78b24.png)

**Comment by d4mation** [comment]
That's really strange about the Menu not working at the top of the page. I'm calling `get_header()`, so the Theme should be taking over from there. I'm going to see if I can reproduce this.

**Comment by jrosebr1** [comment]
If you click on either of the links it takes you to the correct URL, so the call to `get_header()` is definitely pulling out the right URL. But for some reason it's not using the correct text.

**Comment by d4mation** [comment]
Ah, I know exactly what is causing it then. 

I'm filtering `the_title` in order to get things like the Breadcrumbs working properly within X Theme. I'll just need to find a way to prevent it from running on Menu Items. I had none in my test environment, so I missed that that would happen. 

I'll be sure to set up some dummy menu items and go from there!
