### ISSUE TITLE
Include "Administrators" users in search results as well

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#19]
Otherwise, my own username "Adrian" is not included in the search results.
![screen shot 2016-04-15 at 9 28 53 am](https://cloud.githubusercontent.com/assets/759645/14562756/8bef8f5a-02ec-11e6-9cf4-8b4444e39fbe.png)
![screen shot 2016-04-15 at 9 28 20 am](https://cloud.githubusercontent.com/assets/759645/14562757/8bf19282-02ec-11e6-91ed-b689902fcf8b.png)

**Comment by jrosebr1** [comment]
Thanks for including the Administrators in the filter. However, after looking at the database I see that there are a total of four Administrators in the PyImageSearch Gurus database, none of which should be listed in the listing. In that case, I think it's best to update the `if` statement to be `if user is administrator and username is 'Adrian'. Sorry about that!

**Comment by brashrebel** [comment]
There might be a more elegant way to do this than statically defining a username in the condition. WordPress does support multiple roles for user accounts (with some minor issues) so it may make more sense to have a custom default user role and `adrian` can be both an administrator _and_ have the other role as well. Then you'd have more flexibility in the future. Just a thought.

**Comment by d4mation** [comment]
[It seems that there's a pretty nice plugin that helps facilitate this as well](https://wordpress.org/plugins/multiple-roles).

I could make a special Role within the Members Profile plugin and check for that instead of Administrator. The above plugin could then be used to easily assign it rather than hardcoding a "Give @jrosebr1 our new Role as well as Administrator" bit of code in there.

**Comment by jrosebr1** [comment]
I certainly agree that using roles is the more elegant way to resolve this issue. But to be honest, I'd rather keep the dependencies as trim as possible. I'm okay with using hardcoded values for this, even though I fully understand it's not elegant.

**Comment by d4mation** [comment]
Given that, I decided to just change up the query to specifically check for your User when it comes to displaying Admins.

The only drawback is that for the Member Directory, I'm having to check against your `first_name` and `last_name` values as `user_login` is `user_data` rather than `user_meta` so I can't throw it into a Meta Query.

It is checking against your User Name for everything else (Member Profile, JSON Response, Public Profile, etc.), but if you change your First or Last Name using the form you will no longer show within the Directory results. I figure outside of testing that functionality you wouldn't be doing that anyway with your own account, but I wanted to give you a heads up.

**Comment by jrosebr1** [comment]
Thanks for mentioning it :-)
