### ISSUE TITLE
User should be able to preview what their profile looks like to the public

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#23]
After editing my profile page, I can't see what it "looks like to the world" unless I logout of my account and then revisit my profile page. Would be be possible to use an `?preview` query string on the member page to allow the user to view what their profile looks like? Sort of what LinkedIn and Facebook do so you can "see" what others are seeing?

**Comment by d4mation** [comment]
I just added the functionality for this. Should I add a button to access it to the Profile Edit Screen to help insure it is an obvious feature?

**Comment by jrosebr1** [comment]
Yes, add it to the edit screen -- that would be perfect.

**Comment by d4mation** [comment]
As I was adding the button, I figured that making the query parameter `?public` rather than `?preview` made a little more sense, since it shows them what is _already_ saved rather than giving them a _preview_ of their changes.

I went ahead and spruced up the appearance on Mobile to better accommodate it as well.

![image](https://cloud.githubusercontent.com/assets/7770631/14574106/6ecd710e-0327-11e6-94ab-02a91fbf57dc.png)

**Comment by jrosebr1** [comment]
Looks good!
