### ISSUE TITLE
404 text displayed on all headers.

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#29]
In the previous download of the plugin, the headers would either show "Member Directory" or the name of the user. However, now the text says "Oh no!" which is the text used for 404 pages:
![screen shot 2016-04-18 at 6 36 45 am](https://cloud.githubusercontent.com/assets/759645/14601466/17e2b722-0530-11e6-93e0-d3dd998c89aa.png)
![screen shot 2016-04-18 at 6 37 52 am](https://cloud.githubusercontent.com/assets/759645/14601465/17e2811c-0530-11e6-831c-1770f66a3b6e.png)
![screen shot 2016-04-18 at 6 36 07 am](https://cloud.githubusercontent.com/assets/759645/14601467/17e62e52-0530-11e6-9009-2947f2849248.png)

**Comment by d4mation** [comment]
This is very strange as it doesn't seem to do this on my end. I'll have to see if I can reproduce this.

**Comment by d4mation** [comment]
Quick question: Are you using the `Custom 404` X Theme Extension? That's about the only explanation I can come up with for this.

When these pages load, I'm making `global $wp_query` think they are **not** 404 pages in order to prevent a lot of WP Core functionality from taking over so I can sideload my own templates and functions on those slugs.

Since they aren't real Pages, they don't have a `post_id` so it is set to 0. When I fixed the Navigation menu in #14 and #15 I started checking if `post_id` was 0 in my Filter. 

Maybe the `Custom 404` extension does something similar and that's causing problems?

**Comment by jrosebr1** [comment]
Indeed, I am using the Custom 404 X Theme Extension:

![screen shot 2016-04-18 at 5 20 23 pm](https://cloud.githubusercontent.com/assets/759645/14620313/e6fb01dc-0589-11e6-8213-9c4575ae6d50.png)

Do you have the extension on your system? If not, let me know and I can zip it up for you.

**Comment by d4mation** [comment]
I got ahold of the extension and I can confirm that it is what is causing the problem.

I'm going to look into seeing how I can fix this.
