### ISSUE TITLE
Users should not have permission to link to content using the WP "backend".

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#34]
When using the WYSIWYG editor, users should not be able to click the "Or link to existing content" link and open up the list of pages on the PyImageSearch Gurus site. Is there a way to remove this link entirely? And default the "Open link in new tab" to checked?
![screen shot 2016-04-18 at 6 55 35 am](https://cloud.githubusercontent.com/assets/759645/14601900/c26499d4-0532-11e6-8193-7a8dccd75046.png)

**Comment by d4mation** [comment]
Oh, that is certainly no good. I'll need to check to see if there's a Filter or something in Core that I can use to disable that if the User is a Subscriber. They must be able to populate that list since they have the `read` capability by default.

Checking `Open Link in New Tab` likely will need to be done with some JavaScript.

**Comment by d4mation** [comment]
I've Filtered out the ability for Subscribers to load any Internal Links with that tool in the WYSIWYG editor. Since it was showing a blank field that was non-functional, I've hidden it with CSS as well. If they get sneaky and try to unhide it, it won't be any results for them to pick anyway.

![image](https://cloud.githubusercontent.com/assets/7770631/14618812/7f6020ea-0582-11e6-9561-f2e0ba21a769.png)

I'm going to see if there's a better way to handle the `Open Link in New Tab` situation. I'd rather avoid checking it via JavaScript if I can. Edit: Turns out there's no better way to do it :/

**Comment by jrosebr1** [comment]
Perfect, much better!
