### ISSUE TITLE
Formatting of filter buttons

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#40]
This looks like a CSS issue, but the formatting for "Apply Filters" looks off when compared to the "Reset Filters" button. The "Apply Filters" is almost overflowing the button.
![screen shot 2016-05-03 at 7 00 35 am](https://cloud.githubusercontent.com/assets/759645/14981479/8a99ff90-10fd-11e6-9132-e93cf8c46934.png)

**Comment by d4mation** [comment]
Hmm, that's interesting. Just to be certain, have you hard-refreshed? I had to add some CSS to get the buttons looking nicely over there. I cannot remember, but I may have encountered this very issue and fixed it previously.

I'm pretty sure you're using the Renew stack for X Theme based on your screenshots, but are you using any other custom settings within the Customizer? I've got everything at its defaults, so it is possible that's why I'm not seeing the problem on my end.

![image](https://cloud.githubusercontent.com/assets/7770631/14982917/f1da9750-1107-11e6-85a1-eea8bbee502b.png)

**Comment by jrosebr1** [comment]
Correct, I have hard-refreshed and used an incognito window, the issue still persists. You are also correct, I am using Renew stack for X theme. I do have a few custom styles in there, so that's likely where the issue is coming from. Either way, I'll likely end up restlying some things in the future, so we can go ahead and close this.
